"""Provide catalog support for the standalone verification harness."""
from __future__ import annotations

from ..models import AdapterKind, AdapterSpec


def adapter_catalog() -> dict[str, AdapterSpec]:
    """Return the immutable catalog of adapters supported by the harness."""
    specs = [
        AdapterSpec(
            "python",
            "Python 3.11+",
            AdapterKind.EXECUTABLE,
            ("all",),
            commands=("python3", "python"),
            version_args=("--version",),
            optional=False,
            manual_install_note="Install Python 3.11 or newer using your operating-system package manager or python.org.",
        ),
        AdapterSpec(
            "pytest",
            "pytest",
            AdapterKind.PYTHON,
            ("unit", "integration"),
            python_modules=("pytest",),
            pip_requirement="pytest>=8,<10",
            optional=False,
        ),
        AdapterSpec(
            "coverage",
            "coverage.py",
            AdapterKind.PYTHON,
            ("coverage", "public-api"),
            python_modules=("coverage",),
            pip_requirement="coverage>=7,<8",
            optional=False,
        ),
        AdapterSpec(
            "jsonschema",
            "jsonschema",
            AdapterKind.PYTHON,
            ("contracts",),
            python_modules=("jsonschema",),
            pip_requirement="jsonschema>=4.23,<5",
            optional=False,
        ),
        AdapterSpec(
            "javalang",
            "javalang",
            AdapterKind.PYTHON,
            ("ghidra-static",),
            python_modules=("javalang",),
            pip_requirement="javalang>=0.13,<1",
            optional=False,
        ),
        AdapterSpec(
            "pyyaml",
            "PyYAML",
            AdapterKind.PYTHON,
            ("skill-frontmatter",),
            python_modules=("yaml",),
            pip_requirement="PyYAML>=6,<7",
            optional=False,
        ),
        AdapterSpec(
            "build",
            "Python build",
            AdapterKind.PYTHON,
            ("packaging",),
            python_modules=("build",),
            pip_requirement="build>=1.2,<2",
            optional=False,
        ),
        AdapterSpec(
            "capstone",
            "Capstone Python bindings",
            AdapterKind.PYTHON,
            ("disassembly", "matching", "symbolic"),
            python_modules=("capstone",),
            pip_requirement="capstone>=5.0.6,<6",
            optional=True,
        ),
        AdapterSpec(
            "unicorn",
            "Unicorn Python bindings",
            AdapterKind.PYTHON,
            ("dynamic", "functional"),
            python_modules=("unicorn",),
            pip_requirement="unicorn>=2.1.4,<3",
            optional=True,
        ),
        AdapterSpec(
            "z3",
            "Z3 Python bindings",
            AdapterKind.PYTHON,
            ("symbolic", "functional"),
            python_modules=("z3",),
            pip_requirement="z3-solver>=4.15,<5",
            optional=True,
        ),
        AdapterSpec(
            "angr",
            "angr",
            AdapterKind.PYTHON,
            ("angr", "symbolic-memory"),
            python_modules=("angr",),
            pip_requirement="angr>=9.2,<10",
            optional=True,
        ),
        AdapterSpec(
            "fastapi",
            "FastAPI",
            AdapterKind.PYTHON,
            ("service",),
            python_modules=("fastapi",),
            pip_requirement="fastapi>=0.128,<1",
            optional=True,
        ),
        AdapterSpec(
            "uvicorn",
            "Uvicorn",
            AdapterKind.PYTHON,
            ("service",),
            python_modules=("uvicorn",),
            pip_requirement="uvicorn>=0.48,<1",
            optional=True,
        ),
        AdapterSpec(
            "lief",
            "LIEF",
            AdapterKind.PYTHON,
            ("independent-pe",),
            python_modules=("lief",),
            pip_requirement="lief>=0.17,<0.18",
            optional=True,
        ),
        AdapterSpec(
            "java",
            "Java runtime",
            AdapterKind.EXECUTABLE,
            ("ghidra",),
            commands=("java",),
            environment_variables=("JAVA_HOME",),
            root_markers=("bin/java", "bin/java.exe"),
            version_args=("-version",),
            optional=False,
            manual_install_note="Install a Java version supported by the selected Ghidra release.",
        ),
        AdapterSpec(
            "ghidra",
            "Ghidra",
            AdapterKind.DIRECTORY,
            ("ghidra-live", "pcode", "decompiler"),
            commands=("analyzeHeadless", "analyzeHeadless.bat"),
            environment_variables=("GHIDRA_HOME",),
            root_markers=("support/analyzeHeadless", "support/analyzeHeadless.bat"),
            github_repository="NationalSecurityAgency/ghidra",
            release_asset_patterns={"all": ("ghidra_", ".zip")},
            custom_path_kind="directory",
            optional=False,
            manual_install_note="Download an official Ghidra release archive and extract it; select the extracted root directory.",
        ),
        AdapterSpec(
            "dynamorio",
            "DynamoRIO",
            AdapterKind.DIRECTORY,
            ("drcov-live", "runtime-tracing"),
            commands=("drrun", "drrun.exe"),
            environment_variables=("DYNAMORIO_HOME",),
            root_markers=("bin64/drrun", "bin64/drrun.exe", "bin32/drrun", "bin32/drrun.exe"),
            github_repository="DynamoRIO/dynamorio",
            release_asset_patterns={
                "linux-x86_64": ("Linux", ".tar.gz"),
                "windows-x86_64": ("Windows", ".zip"),
                "darwin-x86_64": ("Darwin", ".tar.gz"),
                "darwin-arm64": ("Darwin", ".tar.gz"),
            },
            custom_path_kind="directory",
            optional=False,
            manual_install_note="Download a DynamoRIO release package and select its extracted root or drrun executable.",
        ),
        AdapterSpec(
            "objdiff",
            "objdiff CLI",
            AdapterKind.EXECUTABLE,
            ("objdiff", "matching"),
            commands=("objdiff-cli", "objdiff"),
            environment_variables=("OBJDIFF",),
            github_repository="encounter/objdiff",
            release_asset_patterns={
                "linux-x86_64": ("cli", "linux", "x86_64"),
                "windows-x86_64": ("cli", "windows", "x86_64"),
                "darwin-x86_64": ("cli", "macos", "x86_64"),
                "darwin-arm64": ("cli", "macos", "arm64"),
            },
            custom_path_kind="file",
            optional=False,
            manual_install_note="Install the objdiff release CLI or select the objdiff executable.",
        ),
        AdapterSpec(
            "clang",
            "Clang C compiler",
            AdapterKind.EXECUTABLE,
            ("compiler", "corpus", "coff"),
            commands=("clang", "clang.exe"),
            environment_variables=("CLANG",),
            optional=False,
            manual_install_note="Install LLVM/Clang or select the clang executable.",
        ),
        AdapterSpec(
            "clangxx",
            "Clang C++ compiler",
            AdapterKind.EXECUTABLE,
            ("compiler", "corpus", "cpp"),
            commands=("clang++", "clang++.exe"),
            environment_variables=("CLANGXX",),
            optional=False,
            manual_install_note="Install LLVM/Clang or select the clang++ executable.",
        ),
        AdapterSpec(
            "lld-link",
            "LLD COFF linker",
            AdapterKind.EXECUTABLE,
            ("relink", "whole-image"),
            commands=("lld-link", "lld-link.exe"),
            environment_variables=("LLD_LINK",),
            optional=False,
            manual_install_note="Install LLVM/LLD or select lld-link.",
        ),
        AdapterSpec(
            "llvm-lib",
            "LLVM librarian",
            AdapterKind.EXECUTABLE,
            ("coff-archive",),
            commands=("llvm-lib", "llvm-lib.exe", "llvm-ar"),
            optional=False,
            manual_install_note="Install LLVM tools or select llvm-lib/llvm-ar.",
        ),
        AdapterSpec(
            "llvm-readobj",
            "LLVM object inspector",
            AdapterKind.EXECUTABLE,
            ("independent-coff",),
            commands=("llvm-readobj", "llvm-readobj.exe"),
            optional=False,
            manual_install_note="Install LLVM tools or select llvm-readobj.",
        ),
        AdapterSpec(
            "llvm-objdump",
            "LLVM objdump",
            AdapterKind.EXECUTABLE,
            ("independent-disassembly",),
            commands=("llvm-objdump", "llvm-objdump.exe"),
            optional=False,
            manual_install_note="Install LLVM tools or select llvm-objdump.",
        ),
        AdapterSpec(
            "gcc",
            "GCC C compiler",
            AdapterKind.EXECUTABLE,
            ("compiler-regression",),
            commands=("gcc", "gcc.exe"),
            optional=False,
            manual_install_note="Install GCC or select gcc.",
        ),
        AdapterSpec(
            "gxx",
            "GCC C++ compiler",
            AdapterKind.EXECUTABLE,
            ("compiler-regression",),
            commands=("g++", "g++.exe"),
            optional=False,
            manual_install_note="Install GCC or select g++.",
        ),
        AdapterSpec(
            "cmake",
            "CMake",
            AdapterKind.EXECUTABLE,
            ("native-build",),
            commands=("cmake", "cmake.exe"),
            optional=False,
            manual_install_note="Install CMake or select cmake.",
        ),
        AdapterSpec(
            "ninja",
            "Ninja",
            AdapterKind.EXECUTABLE,
            ("native-build",),
            commands=("ninja", "ninja.exe"),
            optional=False,
            manual_install_note="Install Ninja or select ninja.",
        ),
        AdapterSpec(
            "pip-audit",
            "pip-audit",
            AdapterKind.PYTHON,
            ("dependency-security", "release"),
            python_modules=("pip_audit",),
            pip_requirement="pip-audit>=2.7,<3",
            optional=False,
            manual_install_note="Install pip-audit in the test-suite Python environment.",
        ),
        AdapterSpec(
            "container-runtime",
            "Docker or Podman container runtime",
            AdapterKind.EXECUTABLE,
            ("isolated-workers", "compiler-worker"),
            commands=("docker", "podman", "docker.exe", "podman.exe"),
            version_args=("--version",),
            optional=False,
            manual_install_note="Install Docker or Podman, or select an existing runtime executable.",
        ),
        AdapterSpec(
            "lm-studio",
            "LM Studio CLI",
            AdapterKind.EXECUTABLE,
            ("local-llm", "lm-studio"),
            commands=("lms", "lms.exe"),
            version_args=("--version",),
            optional=True,
            capabilities=("local-loopback-llm", "openai-compatible-chat"),
            manual_install_note="Install the official LM Studio CLI and start a local server before live provider tests.",
        ),
        AdapterSpec(
            "lm-studio-http",
            "LM Studio OpenAI-compatible HTTP endpoint",
            AdapterKind.HTTP_ENDPOINT,
            ("local-llm", "lm-studio", "openai-compatible-chat"),
            environment_variables=("LM_STUDIO_BASE_URL", "X86DECOMP_LM_STUDIO_URL"),
            optional=True,
            capabilities=("local-loopback-llm", "openai-compatible-chat", "structured-output-json"),
            custom_path_kind="url",
            manual_install_note="Start LM Studio's local server and set LM_STUDIO_BASE_URL, for example http://127.0.0.1:1234/v1.",
        ),
        AdapterSpec(
            "ollama",
            "Ollama",
            AdapterKind.EXECUTABLE,
            ("local-llm", "ollama"),
            commands=("ollama", "ollama.exe"),
            version_args=("--version",),
            optional=True,
            capabilities=("local-loopback-llm", "ollama-chat", "structured-output-json"),
            manual_install_note="Install Ollama and start its local API service before live provider tests.",
        ),
        AdapterSpec(
            "llama-server",
            "llama.cpp server",
            AdapterKind.EXECUTABLE,
            ("local-llm", "llama.cpp"),
            commands=("llama-server", "llama-server.exe"),
            version_args=("--version",),
            optional=True,
            capabilities=("local-loopback-llm", "openai-compatible-chat"),
            manual_install_note="Build or install the official llama.cpp llama-server executable.",
        ),
        AdapterSpec(
            "vllm",
            "vLLM server",
            AdapterKind.EXECUTABLE,
            ("local-llm", "vllm"),
            commands=("vllm", "vllm.exe"),
            version_args=("--version",),
            optional=True,
            capabilities=("local-loopback-llm", "openai-compatible-chat", "structured-output-json"),
            manual_install_note="Install vLLM in a supported Python/GPU environment to exercise its OpenAI-compatible server.",
        ),
        AdapterSpec(
            "localai",
            "LocalAI server",
            AdapterKind.EXECUTABLE,
            ("local-llm", "localai"),
            commands=("local-ai", "local-ai.exe", "localai", "localai.exe"),
            version_args=("--version",),
            optional=True,
            capabilities=("local-loopback-llm", "openai-compatible-chat", "structured-output-json"),
            manual_install_note="Install the official LocalAI server executable or provide its path.",
        ),
        AdapterSpec(
            "msvc",
            "User-owned Microsoft C/C++ toolchain",
            AdapterKind.TOOLCHAIN,
            ("historical-msvc", "matching"),
            commands=("cl.exe", "link.exe"),
            environment_variables=("VCINSTALLDIR", "VSINSTALLDIR"),
            root_markers=("bin/Hostx64/x86/cl.exe", "bin/Hostx64/x64/cl.exe", "cl.exe"),
            custom_path_kind="directory",
            optional=True,
            manual_install_note="Select an authorized Visual C++ installation root or Developer Command Prompt environment. Historical proprietary compilers are never downloaded by this suite.",
        ),
    ]
    return {spec.adapter_id: spec for spec in specs}
